version: "3.8"
services:
  db:
    image: postgres:15
    container_name: blog
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-eccentricharry}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changemeinprod!}
      POSTGRES_DB: ${POSTGRES_DB:-blog}
    ports:
      - "5432:5432"
    volumes:
      - blog-data:/var/lib/postgresql/data

volumes:
  blog-data:
